---
- name: Gather Linux System Status Data
  hosts: linux_hosts
  vars:
    ansible_remote_tmp: /var/tmp/ans
    host_key_checking: false
  gather_facts: false
  tasks:
    - block:
        - name: Test Connections
          wait_for_connection:
            delay: 1
            timeout: 10
        - name: Collect facts
          gather_facts:

        - name: Initialize system_status_results
          set_fact:
            system_status_results: []

              # save time, take this from ansible facts
              #        - name: Gather Hostname
              #          shell: hostname
              #          register: hostname_output

              # also gather ansible_uptime_seconds from facts

        - name: Gather Ansible Ping
          ping:
          register: ansible_ping_output

        - name: Gather Disk Capacity
          shell: df -h / | tail -1 | awk '{print $5}'
          register: disk_capacity_output

        - name: Gather Process Usage
          shell: uptime | awk -F, '{ print $5 }' | xargs
          register: proc_usage_output

        - name: Gather App Check for sshd
          service:
            name: sshd
            state: started
          register: app_check_output

        - name: Append Linux data to results
          set_fact:
            system_status_results: |
              {{
                system_status_results + [{
                  "hostname": ansible_fqdn,
                  "ansible_ping": ansible_ping_output.ping,
                  "disk_capacity": disk_capacity_output.stdout.strip(),
                  "proc_usage": proc_usage_output.stdout_lines,
                  "app_check": app_check_output.state,
                  "uptime": ansible_uptime_seconds
                }]
              }}

        - name: Send custom data to web URL
          ansible.builtin.uri:
            url: "http://localhost/post/store_system_status.php?taskid={{ semaphore_vars.task_details.id }}"
            method: POST
            body_format: json
            body: "{{ system_status_results }}"
            headers:
              Content-Type: application/json
            status_code: 200
            return_content: True
          register: postoutput
          delegate_to: localhost

            #        - name: debug
            #          debug:
            #            var: postoutput

      rescue:
        - name: Initialize system_status_results on rescue
          set_fact:
            system_status_results: []

        - name: Handle unreachable hosts
          set_fact:
            system_status_results: |
              {{
                system_status_results + [{
                  "hostname": inventory_hostname,
                  "ansible_ping": "unreachable",
                  "disk_capacity": "0",
                  "proc_usage": ["0"],
                  "app_check": "FAILED",
                  "uptime": 0
                }]
              }}

        - name: Send custom data to web URL - unreachable hosts
          ansible.builtin.uri:
            url: "http://localhost/post/store_system_status.php?taskid={{ semaphore_vars.task_details.id }}"
            method: POST
            body_format: json
            body: "{{ system_status_results }}"
            headers:
              Content-Type: application/json
            status_code: 200
            return_content: True
          register: postoutput
          delegate_to: localhost
