---
- name: Display Facts
  hosts: win
  gather_facts: yes
  tasks:
    - name: Get disk facts
      community.windows.win_disk_facts:

    - name: Output first disk size
      debug:
        var: ansible_facts.disks[0].partitions[2]

