---
- hosts: win
  tasks:
    - name: Install Putty
      win_package:
        path: http://164.225.186.92/software/putty-64bit-0.81-installer.msi
        product_id: '{DDC95F26-92B1-4546-9678-5DC68DF76BA0}'
        arguments:
          - /qn
          - /norestart
        state: present

